version: "3.8"
services:
  secondapp:                   # name of your app service
    build: .                   # build from current directory (needs Dockerfile here)
    container_name: nextjs-secondapp
    restart: always
    ports:
      - "4000:3000"            # ✅ outside port 4000 → inside container port 3000
    env_file:
      - .env.production        # ✅ your environment variables file
    depends_on:
      - mongo2                 # waits until MongoDB starts

  mongo2:                      # MongoDB for second app
    image: mongo:6
    container_name: mongodb2
    restart: always
    ports:
      - "27018:27017"          # ✅ outside port 27018 → inside MongoDB 27017
    volumes:
      - mongodb2_data:/data/db # ✅ keeps your MongoDB data safe even if container stops

volumes:
  mongodb2_data:               # ✅ named volume for persistence
