

services:
  app:
    build: .
    container_name: nextjs-app
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env.production
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: